### ISSUE TITLE
Should okta-rc3 be used instead?

### ISSUE THREAD

**Issue by juansolu** [oktadeveloper/okta-spring-boot-angular-pwa-example#6]
I am currently encountering the issue listed at: https://github.com/stormpath/stormpath-sdk-java/issues/1346

One of the workarounds proposed there was to bump up to okta-rc3, should this be merged into master?

https://github.com/oktadeveloper/okta-spring-boot-angular-pwa-example/blob/7737ff6c252d1194f1650c6eccb68d510dccb7fb/server/pom.xml#L25

**Comment by mraible** [comment]
@juansolu Is this still an issue for you?

**Comment by mraible** [comment]
I changed the example to remove the Stormpath Spring Boot Starter, so closing this issue.
